-- =============================================================================
-- Cyclistic Bike-Share Case Study
-- File:        01_data_cleaning.sql
-- Author:      Abhimanyu Jain
-- Database:    DuckDB
-- Dataset:     Cyclistic Historical Trip Data (July 2025 – June 2026)
--
-- Description:
-- This script performs the complete data preparation workflow including:
--   1. Importing and merging 12 monthly trip datasets
--   2. Cleaning, validating, and filtering out invalid/incomplete records
--   3. Feature engineering (creating derived variables for analysis)
--   4. Exporting the final cleaned dataset for exploratory analysis
-- =============================================================================
